config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  devise_for :users
  resources :events, only: [:show]
  get 'attend_event', to: 'events#attend_event'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/UsersEvents.rb
class Userevent < ApplicationRecord
	has_many: users
	has_many: events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :userevent
	has_many :users, :through => :userevent
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :userevents
  has_many :events, :through => :userevent
end

app/models/userevent.rb
class Userevent < ApplicationRecord
	belongs_to :user
	belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name , :gender])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, only: [:attend_event]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @event_users = @event.users
  end

  def attend_event
      Userevent.create(user_id: current_user.id,event_id: params[:id])
      redirect_to event_path(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def is_event_passed
    if(Date.today < @event.event_date)
      return true
    end
  end

  def is_attended
    record = Userevent.where(user_id: current_user.id, event_id: @event.id).count
    if(record > 0)
      return true
    else
      return false
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/index.html.erb
<center><h1>All Event </h1></center>
<div class="container">
  <h2>Evcent List</h2>         
  <table class="table table-hover">
    <thead>
      <tr>
        <th>S#</th>
        <th>Event Name</th>
        <th>Event Date</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% counter = 1 %>
      <% @events.each do |event| %>
        <tr>
          <td><%= counter %></td>
          <td><%= event.title %></td>
          <td><%= event.event_date %></td>
          <td><%= link_to (event_path(event.id)) do %><i class="fa fa-eye" aria-hidden="true"></i><% end %></td>
        </tr>
      <% counter = counter + 1 %>
      <%  end %>
    </tbody>
  </table>
</div>

  

app/views/events/show.html.erb
<div class= "container">
  <div class="row">
    <div class="col-sm-6">
      <div class="card">
       <div class="card-header">Event Detail</div>
        <div class="card-body">
          <h5 class="card-title"><%=@event.title %></h5>
          <p class="card-text"><%=@event.description %><br>Event Date:<%=@event.event_date %> </p>
          <% if( current_user && is_event_passed ) %>
             <% if( is_attended ) %>
              <a href="#" class="btn btn-primary">Alredy attended</a>
             <% else %>
              <%= link_to "attend", (attend_event_path(id: @event.id)), class: "btn btn-primary" %>
             <% end %>    
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card">
      <div class="card-header">Users who attend the event</div>
        <div class="card-body">
        <table class="table table-hover">
    <thead>
      <tr>
        <th>S#</th>
        <th>Name</th>
        <th>Gender</th>
      </tr>
    </thead>
    <tbody>
         <% counter = 1 %>
          <% @event_users.each do | user | %>
        <tr>
          <td><%= counter %></td>
          <td><%= user.name %></td>
          <td><%= user.gender %></td>
        </tr>
        <% counter = counter + 1 %>
        <% end %>
    </tbody>
  </table>  
        </div>
      </div>
    </div>
  </div>
</div> 

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Event</a>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if current_user %>
      <li class="nav-item">
        <a class= "nav-link">Hi <%= current_user.name %></a>
      </li>
      <li class="nav-item active">
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete , class: "nav-link"%>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Sign up', new_user_registration_path, class: "nav-link"%>
      </li>
       <li class="nav-item">
        <%= link_to 'Sign in', new_user_session_path ,class: "nav-link" %>
       </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAPP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render partial: "layouts/navbar" %>
 <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>